### PR TITLE
Feature measure decibel

### PR DESCRIPTION
**Pull request by xy124**
Please test on android and ios.
In the settings-tap is a dB-label. 
If not muted(and the Toggle Decibel Meter is activated), the volumeProfile should change to _outdoor_ when dB-level is greater than 90.

### CODE REVIEW

**Comment by Aedge90** [comment]
Tested it on android 5.1.1:
The volume only updates once when I toggle the Toggle decibel meter. So I cant see what my current db value is. Also for me it is not clear if an active toggle means "recording db" or "not recording db"

**Comment by xy124** [comment]
Ah ok thanks for the testing @Aedge90 . 
Strange that the current volume does not change as it even does so on my Blackberry. Can you give me logcats output?

**Comment by Aedge90** [comment]
I added $apply. Now it updates for me too

**Comment by xy124** [comment]
Thanks man great :+1:  !

**Comment by Aedge90** [comment]
I tried to test the 90 dB thing but when I tried it my ears hurt :D Maybe we can go a bit lower ^^
What happens for me is that the volume changes to 90% but the profile does not get selected

**Comment by xy124** [comment]
@Aedge90 also recognized that. Just fixed it... was a really stupid bug because angular overrides JSON.stringify and the used json filter does use the pretty flag :/

**Comment by xy124** [comment]
Now again rebased on master and ready to pull. If one could test on android would be great but all _should_ work ;)

**Comment by Aedge90** [comment]
Tested it again. works almost perfect now. But I still found an issue, sorry :/ Here is what I did:
1. started the app. Did some volume recording
2. Closed the app via the hardware back button
3. Opened the app again
--> audio recording does not work anymore. Logcat shows this error:

```
06-07 10:08:31.920: I/android.media.AudioRecord(10929): startRecording
06-07 10:08:31.935: I/AudioRecordPermission(10929): remindWithResult:false
06-07 10:08:31.935: E/AudioRecord(10929): start() status -38
06-07 10:08:31.935: I/AudioRecord(10929): sendStateChangedIntent, state=1
```

**Comment by xy124** [comment]
Hope I fixed it :dash:  as I now pause and resume the DBMeter if app is moved to background. Would be cool if you could retest @Aedge90 :)

**Comment by Aedge90** [comment]
Yes everything is working now :)

**Comment by estherteta** [comment]
Test on iphone it works well but the same initial problem as Achim, when I move the app into the background and open it again the recording stops.

**Comment by xy124** [comment]
@estherteta which version did you test? can you send me a complete log please?

**Comment by estherteta** [comment]
@xy124 hm when i tried it again it actually works, but when i tried it several times it stops. the logcat didn't show any error it only shows the console log you put.

**Pull request merged**
