### PR TITLE
Slider ScanDuration

### PR DESCRIPTION
**Pull request by domkrel**
Removed Scan-Duration-TextBox
Added Scan-Duration-Slider

### CODE REVIEW

**Comment by Aedge90** [comment]
Works for me but it would probably be a good idea to still have a String saying "Scan duration" so that users know what it is about. Also it would be nice to see the actual value that was set. At the moment you dont know how many seconds are set

**Comment by Aedge90** [comment]
Sorry to tell you but you have to do a lot of rebasing as we have lots of new features merged into master

**Comment by Blackclaws** [comment]
Rebasing has been done. Further changes should be done on this latest version. I agree with Achim about the Scan Duration part.

However this also means we should write something about The volume too.

**Comment by domkrel** [comment]
Yeah. You are right.
It was already part of the code but it looked awful.
Will try it again to make it nice.

**Comment by domkrel** [comment]
I added a string "Scan duration" + the number of seconds
So you actually now what the position of the slider means.

Rebased it on master already

**Pull request merged**
