### PR TITLE
Feature motion sensor

### PR DESCRIPTION
**Pull request by domkrel**
Based on Fix issue#59 

Added the ability to read the motion sensor of your phone.
It displays the 3 axis on the status tab.
You can start and stop to capture the data.

### CODE REVIEW

**Comment by domkrel** [comment]
Please test if I added all dependencies correct (bower, plugin) and you can install without any problems.

**Comment by Aedge90** [comment]
When I click on Show motion, the motion is displayed. But I still get the following error:

```
06-03 11:21:01.765 1421-1501/de.fau.amos.groupOne.BLERemote I/SensorManagerFlow: registerListenerImpl
                                                                                 java.lang.Exception
                                                                                     at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:118)
                                                                                     at android.hardware.SensorManager.registerListener(SensorManager.java:775)
                                                                                     at android.hardware.SensorManager.registerListener(SensorManager.java:682)
                                                                                     at org.apache.cordova.devicemotion.AccelListener.start(AccelListener.java:157)
                                                                                     at org.apache.cordova.devicemotion.AccelListener.execute(AccelListener.java:107)
                                                                                     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                                                                                     at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
                                                                                     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
                                                                                     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
                                                                                     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                                                     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                                     at android.os.HandlerThread.run(HandlerThread.java:61)

```

Then I Hide the Motion and unhide it again. Then the values dont update anymore and I get the above error again. So I get the error everytime I unhide.

Also there is a typo. It should be smartphone motions.

This branch is a bit weird. It contains my pull request on issue 59 and a merge commit.

**Comment by domkrel** [comment]
Thanks achim
Where does the error show up? In your console or in the app?
Travis failed also. Need to find out why it runs for me.

**Comment by Aedge90** [comment]
The error shows up in the logcat output. The app itself is working as it should even though the error is already shown. only when I click show motion a second time the values do not update anymore and the same error is shown again

**Pull request closed without merging**
