### PR TITLE
Feature sqlite

### PR DESCRIPTION
**Pull request by domkrel**
Based on master
Store graph data persistent
Use SQLite cordova plugin

### CODE REVIEW

**Comment by Aedge90** [comment]
Is there any way to test that? It works in the sense that it does not break anything ^^

**Comment by domkrel** [comment]
Well. you will need a sensor tag to test it.
But still the travis checks fail.
Sebastian said he can build the docker locally. But travis cant :-/

**Comment by Aedge90** [comment]
Sebastian fixed it. So you can rebase on master and Travis should work fine again

**Comment by xy124** [comment]
```
karma start tests/unit-tests.conf.js
```

throws errors:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  TypeError: null is not an object (evaluating 'db.transaction')
  at /home/xy124/workspace/amos-ss16-proj1/www/lib/ngCordova/dist/ng-cordova.js:6595
PhantomJS 2.1.1 (Linux 0.0.0): Executed 14 of 15 ERROR (0 secs /PhantomJS 2.1.1 (Linux 0.0.0): Executed 14 of 15 ERROR (0.066 secs / 0.165 secs)
```

**Pull request merged**
