### PR TITLE
Feature graph changes

### PR DESCRIPTION
**Pull request by domkrel**
Based on Master
Changed Graph (behaviour)
Added Warning if no graph-data is available

### CODE REVIEW

**Comment by domkrel** [comment]
What the hell is now wrong?

**Comment by Aedge90** [comment]
Nothing :D I restarted the build and now it just works

**Comment by Aedge90** [comment]
Do you also have the issue that if you drag the graph, while not connected to a device anymore, then it says that no data is available?

**Comment by domkrel** [comment]
No. I dont get the error

**Comment by estherteta** [comment]
I tried it on the iphone and my android phone, I also get "no data available, please connect to a device" when i tried to drag the graph even when the device still connected. When i tried to connect again the graph doesn't show up.

The logcat says:

2016-06-24 19:00:34.756 BLE Remote[7316:2898717] Width of bar is NaN
2016-06-24 19:00:34.756 BLE Remote[7316:2898717] Number of Bars: NaN

**Comment by domkrel** [comment]
I don´t have a device this week.
It worked fine for me.

We just test: If the graph has data to show, show the graph. Otherwise, don´t show it:

if($scope.data[0].length > 0) {
    $scope.showGraph = true;
}
else {
    $scope.showGraph = false;
}

This get called in createAndSetDataSlice() which get called each time if you get new data. The createAndSetDataSlice() method also handels the drag-back by setting the start/end point of data.

You can try to throw out the if-else-part and watch if the graph has any problems.
Maybe you can also print the data[0]-array to check if there is data in.

**Comment by domkrel** [comment]
I was not able reproduce the issue again.
My phone did not let me drag and drop. But that is a well known bug of my phone.

I added some logic to make sure, that we are never out of bound of the dataStorage-array.

Can someone please test?

**Comment by Blackclaws** [comment]
Still does not work. I'll try to fix the error

**Pull request merged**
