### PR TITLE
Feature tour

### PR DESCRIPTION
**Pull request by xy124**
Finally I could fullfill the acceptancecriteria... if it passes your on device tests which I hereby demand ;)

As there was no working plugin for ionic I had to create more or less an own one which took quite a lot effort...

### CODE REVIEW

**Comment by Aedge90** [comment]
I can only see a blank screen now. My error log:

```
06-27 14:22:24.697: E/AndroidProtocolHandler(7944): Unable to open asset URL: file:///android_asset/www/lib/bootstrap/docs/assets/css/bootstrap.css
06-27 14:22:25.548: I/chromium(7944): [INFO:CONSOLE(38)] "Running in Cordova, will bootstrap AngularJS once 'deviceready' event fires.", source: file:///android_asset/www/js/init.js (38)
06-27 14:22:25.681: I/HwSecImmHelper(7944): mSecurityInputMethodService is null
06-27 14:22:25.682: I/HwSecImmHelper(7944): mSecurityInputMethodService is null
06-27 14:22:25.701: I/chromium(7944): [INFO:CONSOLE(40)] "Deviceready event has fired, bootstrapping AngularJS.", source: file:///android_asset/www/js/init.js (40)
06-27 14:22:26.089: I/chromium(7944): [INFO:CONSOLE(26771)] "TypeError: Cannot read property 'startTutorial' of undefined
06-27 14:22:26.089: I/chromium(7944):     at new <anonymous> (file:///android_asset/www/js/controllers/tour.js:68:22)
06-27 14:22:26.089: I/chromium(7944):     at Object.invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:17972:19)
06-27 14:22:26.089: I/chromium(7944):     at $controllerInit (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:23374:34)
06-27 14:22:26.089: I/chromium(7944):     at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:22312:34)
06-27 14:22:26.089: I/chromium(7944):     at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21680:13)
06-27 14:22:26.089: I/chromium(7944):     at publicLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:21560:30)
06-27 14:22:26.089: I/chromium(7944):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:15062:27
06-27 14:22:26.089: I/chromium(7944):     at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30372:28)
06-27 14:22:26.089: I/chromium(7944):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30472:25)
06-27 14:22:26.089: I/chromium(7944):     at bootstrapApply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:15060:15)", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (26771)
06-27 14:22:26.112: I/chromium(7944): [INFO:CONSOLE(40)] "tanslating to: ar-sy", source: file:///android_asset/www/js/app.js (40)
06-27 14:22:26.136: W/cr_BindingManager(7944): Cannot call determinedVisibility() - never saw a connection for the pid: 7944
```

**Comment by xy124** [comment]
@Aedge90 did u bower update?

**Comment by Aedge90** [comment]
ah sorry no I totally forgot

**Comment by Aedge90** [comment]
Oh yeah looks very very nice :) But I can only go to the next tutorial by pressing exactly into the tiny white triangle, which is very small. Is this also the case for you?

**Comment by xy124** [comment]
^^Yes. I can try to enlarge it...
Please test also the tour tip for the db meter... that somehow does strange things sometimes

**Comment by Aedge90** [comment]
Hmmm Ok I now noticed the tooltips sometimes point to strange locatoins

**Comment by xy124** [comment]
^^ yep I know that also only happens/does not happen if one was on some tabs before one starts the tutorial. I removed the critical tourtip on the decibelMeter. Can u retest pls?

**Comment by Aedge90** [comment]
Ok this works very nice now for me  :)  (android 6.0) The tooltips point to the right spots and you can move to the next or previous tutorial even without hitting exactly the white button, which makes it easier now than before

**Comment by xy124** [comment]
@aedge90 can you please test if in this branch the language gets resetted for you as described in #124 ? I guess I tested it with this branch

**Comment by Aedge90** [comment]
It also does not get reset in this branch. I quit the app and restart and the language is still the same and the checkmark in the right spot. However I noticed that now you always show the advanced setting when starting the app, which makes advanced settings kind of unnecessary

**Comment by Aedge90** [comment]
I also found a reproduceable freezing bug. If the app is scanning for devices it ALWAYS freezes after you klick the "next" button on the tooltip "auf dem statusreiter kann man soch mit höhrgeräten verbinden "

**Comment by Aedge90** [comment]
Ok very nice :) the freeze bug is now fixed

**Comment by Aedge90** [comment]
I rebased it on master. Still works well ^^ If nobody says otherwise I will merge it today in the evening

**Pull request merged**
