### PR TITLE
Feature motion sensor

### LINKED ISSUE #59: Mute button in Landscape mode
Tested on Android 5.1.1
1. use the app in landscape mode
2. turn mute on

=> a large portion of the app is now not visible anymore

### PR DESCRIPTION
**Pull request by domkrel**
New try.
Based on fix#59
Added cordova-plugin
Show motion sensor data

### CODE REVIEW

**Comment by domkrel** [comment]
Please test again.
Added New Plugin to another file. Now it should work.

Just need to find out why all Tests failed...

**Comment by domkrel** [comment]
Travis likes my work now.

Can someone please test if the error achim mentioned is also gone?

**Comment by Aedge90** [comment]
Tested it again on Android 5.1.1. Still when I click on Show motion, the motion is displayed, but I still get the following error:

```
06-04 17:00:13.080: I/SensorManagerFlow(25888): java.lang.Exception
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:118)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.hardware.SensorManager.registerListener(SensorManager.java:775)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.hardware.SensorManager.registerListener(SensorManager.java:682)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.devicemotion.AccelListener.start(AccelListener.java:157)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.devicemotion.AccelListener.execute(AccelListener.java:107)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.os.Handler.dispatchMessage(Handler.java:102)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.os.Looper.loop(Looper.java:135)
06-04 17:00:13.080: I/SensorManagerFlow(25888):     at android.os.HandlerThread.run(HandlerThread.java:61)
```

Then I Hide the Motion and unhide it again. Then the values dont update anymore and I get the above error again. So I get the error everytime I unhide. Also you still have the typo in there

**Comment by domkrel** [comment]
@Aedge90 I am not able to reproduce the error.
Did also not find anything about it on the net.
It should not be the android version, cause you have a higher one than my device has.
Did you install all the plugins correctly? I built our project from scratch and everything was fine.

**Comment by Aedge90** [comment]
Created a fresh repo with git clone. Followed our readme. But still I have the same error :(

**Comment by domkrel** [comment]
Okay. I guess we need more tester to find out the reason.

**Comment by estherteta** [comment]
Test it on both iphone and my android 5.1.1 and there's no error shown in the logcat. It works fine when I show and hide the motion.

**Comment by domkrel** [comment]
Thank you estherteta!
3x good
1x error
Good to know. It´s just achim´s device again ;-)

If it is really just achim´s device we could pull it into master + open issue to solve the achim-bug

**Pull request merged**
