### PR TITLE
Feature rtl checkboxes

### PR DESCRIPTION
**Pull request by Aedge90**
All checkboxes are now displayed on the left if the language is changed to arabic

### CODE REVIEW

**Comment by Aedge90** [comment]
Hmm I now realized that my changes in this feature make the app freeze everytime (!) I go to the graph tab. Dont know if it is the same issue as issue #76 . It just freezes and I do not get any logcat output at all when it happens. Do others also have this problem with this branch?

**Comment by xy124** [comment]
Interesting! Have you checked the errorlog in the js debug console?

**Comment by Aedge90** [comment]
I think that should also be displayed by logcat. However I now realized that the app froze everytime (!) even after I overwrote my installation with commits of older features. That was very strange as theses features used to work. So I completely uninstalled the app and reinstalled it again. Now it works again :D no problem at all and no chance to make it freeze even if I try. So in short: reinstalling the app completely solved the freezing bug here

**Comment by xy124** [comment]
So the bug might have something to do with the persisting of data?
Do you remember if it was introduced after or before the datbase for persisting the measurements?

**Comment by Aedge90** [comment]
Dont know exactly but as this error persists through different versions of the app I think it must have something to do with persistence, yes.

**Comment by domkrel** [comment]
As far as i remember the first freezing-bug appeared before the persistence was merged.
It happend in the period of time when felix and esther were fighting with the accelerometer-sensor.

**Pull request merged**
