### PR TITLE
Feature gui themes

### PR DESCRIPTION
**Pull request by xy124**
Please test if it works for ios and android.
`./selectTheme.sh` should have impact on the app-icon and on the in-app colors.

**New Dependencies:**

```
 npm -g i cordova-icon
 sudo apt-get install imagemagick inkscape
```

### CODE REVIEW

**Comment by Aedge90** [comment]
Very nice :D
I still have the following problems: 
First I run "./selectTheme.sh"
Then "ionic run android --device"
Then the following errors show up:

> cp: no such file or directory: /home/achim/workspaces/AMOS/amos-ss16-proj1/platforms/android/res/drawable-ldpi/icon.png
> cp: no such file or directory: /home/achim/workspaces/AMOS/amos-ss16-proj1/platforms/android/res/drawable-mdpi/icon.png
> cp: no such file or directory: /home/achim/workspaces/AMOS/amos-ss16-proj1/platforms/android/res/drawable-hdpi/icon.png
> cp: no such file or directory: /home/achim/workspaces/AMOS/amos-ss16-proj1/platforms/android/res/drawable-xhdpi/icon.png
> cp: no such file or directory: /home/achim/workspaces/AMOS/amos-ss16-proj1/platforms/android/res/drawable-xxhdpi/icon.png
> cp: no such file or directory: /home/achim/workspaces/AMOS/amos-ss16-proj1/platforms/android/res/drawable-xxxhdpi/icon.png

Then the app starts automatically on my device but with the OLD theme. Only the app icon has changed. Even if i start the app by clicking the new icon I still have the old theme. However if I run "ionic run android --device" again then the theme inside the app also changes

**Comment by xy124** [comment]
Ok I hope I fixed both of your issues. Especially the second took me 2 h of investigation on where cp is called from ionic build tools and then I found the trivial solution you can see in the git diffs :/

Well please retest on android(e.g. @Aedge90) and also on ios (@estherteta).

Cheers, Sebastian

**Comment by Aedge90** [comment]
Yes both issues are fixed :) works really nice now :)

**Comment by estherteta** [comment]
it also works very nice on ios ;)

**Comment by Aedge90** [comment]
Ok then this branch is ready for merging :)

**Pull request merged**
